import { valPw, valUsername } from "./loginhelper";
import {
  dateToStr,
  dateToDaysAndTime,
  getHAgo,
  dateToTime,
  dateToDay,
} from "./dateManipulation";
import {
  getLocation,
  announceMessage,
  tryLogin,
  getData,
  getConvo,
  getReport,
  getUserInfo,
  getLastmeal,
  getDateMeal,
  postVoiceMsg,
  deleteFood,
  editFoodGroup,
  addFood,
  getAnomalies,
  announceReminder,
  deleteReminder,
  getAllMedReminders,
  getMockReport,
} from "./apiRequests";
import { getTickVal, getCategories } from "./chartHelper";

export {
  valPw,
  valUsername,
  dateToStr,
  dateToDaysAndTime,
  getHAgo,
  dateToTime,
  dateToDay,
  announceMessage,
  tryLogin,
  getData,
  getConvo,
  getTickVal,
  getCategories,
  getReport,
  getUserInfo,
  getLastmeal,
  getDateMeal,
  postVoiceMsg,
  getLocation,
  deleteFood,
  editFoodGroup,
  addFood,
  getAnomalies,
  announceReminder,
  deleteReminder,
  getAllMedReminders,
  getMockReport,
};
